#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=24:00:00

set -e 
module load anaconda3/personal

source activate gubbins_sim

cd ~/gubbins_testing

mkdir -p de-nested-summaries_pareto_20k
## Run the gubbins_ppv 
START=$SECONDS
Rscript --vanilla ./gubbins_sim/R/de-nesting_recombination_events.R \
--summary-dir ./sim_summaries_pareto_20k/ --threads 32 --out ./de-nested-summaries_pareto_20k/
END=$(( SECONDS - START ))
printf "Took this long to run %s (S) \n" $END 
