#PBS -l select=1:ncpus=1:mem=24gb:cpu_type=rome
#PBS -l walltime=48:00:00
#PBS -J 1-10

set -e
module load anaconda3/personal

source activate gubbins_git

## Switch to the run directory 
cd ~/../ephemeral/gubbins_testing/simul_data/time_tests/

## Get the run models 
MODEL=$( head -n $PBS_ARRAY_INDEX ~/gubbins_testing/iqtree_1000_runs.txt | tail -n 1)
REP=$( echo $MODEL | awk -F "-" '{print $2"_"$3}')
REP_DASH=$( echo $MODEL | awk -F "-" '{print $2"-"$3}')
#LENGTH=$( echo $MODEL | awk -F "-" '{print $1}')
##Conditional statement for the reconstructions 
cd "${REP}_data"

for K in {1..2};
do

if [ $K -eq 1 ]
then
    PARETO="0"
    REC="1"
else
    PARETO="20000"
    REC="0.1"
fi

BASIO="sim-branch-0.1-rec-${REC}-length-100-pareto-${PARETO}"
cd $BASIO
echo $PWD
START_GUB=$SECONDS
iqtree -v -s *.aln -T 1 -m JC --prefix "${BASIO}"
END_GUB=$(( SECONDS - START_GUB ))
cd ../

done
echo "Finished the runs for this model -  ${MODEL}-${PBS_ARRAY_INDEX}" >> "./models_finished_branch.txt"
