#PBS -l select=1:ncpus=1:mem=12gb:cpu_type=rome
#PBS -l walltime=48:00:00
#PBS -J 1-100

set -e
module load anaconda3/personal

source activate gubbins_git

## Switch to the run directory 
cd ~/../ephemeral/gubbins_testing/iqtree_times

## Get the run models 
MODEL=$( head -n $PBS_ARRAY_INDEX ~/gubbins_testing/iqtree_reps.txt | tail -n 1)

SIMUL_LOC="/rds/general/user/jd2117/ephemeral/gubbins_testing/simul_data/length_tests/"
REP=$( echo $MODEL | awk -F "-" '{print $2"_"$3}')
REP_DASH=$( echo $MODEL | awk -F "-" '{print $2"-"$3}')
LENGTH=$( echo $MODEL | awk -F "-" '{print $1}')
##Conditional statement for the reconstructions 
	cd "${REP}_runs"
        BASIO="sim-branch-0.1-rec-0.5-length-${LENGTH}"
	ALNFILE="${SIMUL_LOC}${REP}_data/${BASIO}/${BASIO}-exact.aln"
	if [ -d $BASIO ]
	then
		cd $BASIO
	else
		mkdir -p $BASIO
		cd $BASIO
	fi

	## Get the alignment file
	MAIN_MODEL="raw-raw-raw-${REP_DASH}-sim-branch-0.1-rec-0.5-length-${LENGTH}-JC-JC"
	if [ -d $MAIN_MODEL ]
	then
		rm -r $MAIN_MODEL
		mkdir $MAIN_MODEL
	else
		mkdir $MAIN_MODEL

	fi
	cd $MAIN_MODEL

	cp $ALNFILE ./
   	TIME_PREFIX="${MAIN_MODEL}-${REP_DASH}-seq-${line}"
	echo $PWD
	START_GUB=$SECONDS
	iqtree -v -s *.aln -T 1 -m JC --prefix "raw-raw-raw-${REP_DASH}-sim-branch-0.1-rec-0.5-length-${LENGTH}-JC-JC"
	END_GUB=$(( SECONDS - START_GUB ))
	rm *.aln
	PROC=$(cat /proc/cpuinfo | grep 'model name' | uniq)
	echo "Took this long for ${TIME_PREFIX} run, $END_GUB" > "../${MAIN_MODEL}_time.txt"
	echo "Used this processor for the runs: $PROC" >> "../${MAIN_MODEL}_time.txt"
	cd ../../../
	

echo "Finished the runs for this model -  ${MODEL}-${PBS_ARRAY_INDEX}" >> "./models_finished_branch.txt"
