#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=24:00:00

set -e 
module load anaconda3/personal

source activate gubbins_sim

cd ~/gubbins_testing/gubbins_3.3_run_data/

## Run the gubbins_ppv 
START=$SECONDS
Rscript --vanilla ../gubbins_sim/R/gubbins_ppv_thesis.R --embl-dir ./pareto_0_snpz/ \
--tree-dir ./pareto_0_trees/ --summary-dir ./de-nested-summaries_pareto_0/ --threads 32 \
--out pareto_0_ppv_denested.csv
END=$(( SECONDS - START ))
printf "Took this long to run %s (S) \n" $END 
