#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=24:00:00

set -e 

module load anaconda3/personal

source activate gubbins_sim

cd ~/gubbins_testing/gubbins_3.3_run_data/

mkdir -p pareto_20k_snpz 
cd pareto_20k_snpz
bash ../../gubbins_sim/bash/snp_classifier.sh ../pareto_20k_gubbins_embls ../pareto_20k_gubbins_gffs 32 \
../../gubbins_sim/R/snp_classifier.R 

echo "Done on the SNP classifier!!!"


