#PBS -l select=1:ncpus=1:mem=24gb:cpu_type=rome
#PBS -l walltime=24:00:00
#PBS -J 1-170

set -e
module load anaconda3/personal

source activate gubbins_git

## Switch to the run directory 
cd ~/../ephemeral/gubbins_testing/snp_runs

## Get the run models 
MODEL=$( head -n $PBS_ARRAY_INDEX ~/gubbins_testing/snp_tests_models.txt | tail -n 1)

SIMUL_LOC="/rds/general/user/jd2117/ephemeral/gubbins_testing/simul_data/orig_simul/simul_data/pareto_0/"
REP=$( echo $MODEL | awk -F "-" '{print $4"_"$5}')
REP_DASH=$( echo $MODEL | awk -F "-" '{print $4"-"$5}')
FIRST_TREE=$( echo $MODEL | awk -F "-" '{print $1}')	
MAIN_TREE=$( echo $MODEL | awk -F "-" '{print $2}')
MAR=$( echo $MODEL | awk -F "-" '{print $3}')
MAIN_MODEL="${FIRST_TREE}-${MAIN_TREE}-${MAR}"
BRANCH=$(echo $MODEL | awk -F "-" '{print $7}')
REC=$(echo $MODEL | awk -F "-" '{print $9}')

##Conditional statement for the reconstructions 
cd "${REP}_runs"
BASIO="sim-branch-${BRANCH}-rec-${REC}"
if [ -d $BASIO ]
then
	cd $BASIO
else
	mkdir -p $BASIO
	cd $BASIO
fi

	## Assumes you have already gubbins duh!
	
cd $MAIN_MODEL

python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *-min-snp-2.branch_base_reconstruction.embl --output "min-snp-2-${REP_DASH}-${BASIO}-JC-JC.embl_csv" --threads 1 
python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *-min-snp-3.branch_base_reconstruction.embl --output "min-snp-3-${REP_DASH}-${BASIO}-JC-JC.embl_csv" --threads 1 

cd ../../../

	
echo "Finished the runs for this model -  ${BASIO}-rep-${REP_DASH}-${PBS_ARRAY_INDEX}" >> "./snp_class_finished_branch.txt"
