#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=00:30:00
#PBS -J 1-9

set -e
module load anaconda3/personal

source activate bioperl

cd ~/gubbins_testing/simul_data 



RECCERS=$(head -n $PBS_ARRAY_INDEX ~/gubbins_testing/gubbins_sim/data/decimals_0.1s.txt | tail -n 1)

if [ $RECCERS == "0.1" ]
then
	echo "wassssssssup"
else

bash ../gubbins_sim/bash/simul_script.sh $RECCERS 0.5 \
~/gubbins_testing/simul_data/strep_53_uc.aln \
~/gubbins_testing/simul_data/26_phage.mfa 
fi
