#PBS -l select=1:ncpus=2:mem=12gb
#PBS -l walltime=24:00:00
#PBS -J 1-18
set -e
module load anaconda3/personal

source activate gubbins_git

cd ~/gubbins_testing/18_ft_iq_jar

if [ $PBS_ARRAY_INDEX -eq 1 ]
then
	BASSYS=$(basename /rds/general/user/jd2117/home/gubbins_testing/simul_data/branch_and_rec_alternating_constant.txt)
	echo $BASSYS > models_failed.txt
	if [ -f models_finished.txt ]
	then
		rm models_finished.txt
	fi
else
	sleep 3m
fi



CURRENT_DAT=$(head -n $PBS_ARRAY_INDEX ../simul_data/branch_and_rec_alternating_constant.txt | tail -n 1)
DAT_BASE=$(basename $CURRENT_DAT)
DAT_ALN="${DAT_BASE}/${DAT_BASE}.aln"

if [ -d $DAT_BASE ]
then 
	rm -r $DAT_BASE

	mkdir $DAT_BASE
else
	mkdir $DAT_BASE
fi
cd $DAT_BASE

echo "/rds/general/user/jd2117/home/gubbins_testing/simul_data/${DAT_ALN}" > aln_file.txt

START_GUB=$SECONDS
time python ~/gubbins/python/run_gubbins.py --prefix "ft-iq-jar-${DAT_BASE}" \
--use-time-stamp --threads 2 --verbose \
--tree-builder iqtree --first-tree-builder fasttree \
--model JC "/rds/general/user/jd2117/home/gubbins_testing/simul_data/${DAT_ALN}" 
END_GUB=$(( SECONDS - START_GUB ))
python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *branch_base* \
--output "ft-iq-jar-${DAT_BASE}.embl_branch.csv" --threads 1

echo $DAT_BASE >> ../models_finished.txt
FAIL_LINE=$(grep -n $DAT_BASE ../models_failed.txt | awk -F ":" '{print $1}')
sed -i "${FAIL_LINE}d" ../models_failed.txt

printf "Finished in %s (S) \n" $END_GUB

