#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l walltime=24:00:00

set -e
module load anaconda3/personal

source activate gubbins2_env

cd ~/gubbins_testing/

MODEL="ft_raxml_join_pyjar"
if [ -d $MODEL ]
then
	rm -r $MODEL
	mkdir $MODEL
else
	mkdir $MODEL

fi
cd $MODEL
BASIO="pyjar_testing"
START_GUB=$SECONDS
python -m memory_profiler ~/gubbins/python/run_gubbins.py --prefix "${MODEL}-${BASIO}" --use-time-stamp --threads 1 --verbose \
--tree-builder raxml --first-tree-builder fasttree --no-cleanup \
--model JC ../simul_data/sim-branch-0.1-rec-0.9/sim-branch-0.1-rec-0.9.aln 
END_GUB=$(( SECONDS - START_GUB ))
echo "finsihed with gubbins run on $END_GUB (s)"

