#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l walltime=24:00:00

set -e 

mkdir -p ~/../ephemeral/gubbins_testing/untarred_simul 
cd ~/../ephemeral/gubbins_testing/untarred_simul 
cp /rds/general/user/jd2117/home/gubbins_testing/gubbins_3.3_run_data/simul_data.tar.gz ./
TAR_START=$SECONDS
tar -xzvf ./simul_data.tar.gz 
TAR_END=$(( SECONDS - TAR_START ))
echo "Tar time is ${TAR_END} (s) " > tar_times.txt 


