#PBS -l select=1:ncpus=10:mem=32gb:cpu_type=rome
#PBS -l walltime=48:00:00
#PBS -J 1-10

set -e 
module load anaconda3/personal

source activate gubbins_update_rec

THREADS=$PBS_ARRAY_INDEX
cd ~/../ephemeral/gubbins_testing/pmen1_runs/
RUN_DIR="rnj_rnj_jar_${THREADS}_threads"
if [ -d $RUN_DIR ]
then
	rm -r $RUN_DIR
	mkdir $RUN_DIR
	cd $RUN_DIR
else
	mkdir $RUN_DIR
	cd $RUN_DIR
fi

START_GUB=$SECONDS
/usr/bin/time -v python ~/gubbins_jit/gubbins/python/run_gubbins.py --prefix pmen1_rnj_rnj_jar \
--use-time-stamp --model JC --first-model JC \
--threads $THREADS --verbose --tree-builder rapidnj --first-tree-builder rapidnj \
~/gubbins_testing/pmen1_data/pmen1_421_aln.aln > gubbins_log 2>&1 
END_GUBBINS=$(( SECONDS - START_GUB ))
PROC=$(cat /proc/cpuinfo | grep 'model name' | uniq)
echo "Took this long for pmen1 ft rax jar run with $THREADS threads, $END_GUB" > "./pmen1_gubb_time.txt"
echo "Used this processor for the runs: $PROC" >> "./pmen1_gubb_time.txt"
python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *branch_base_reconstruction.embl \
--output "pmen1_ft_rax_jar.embl_csv" --threads 1



