#PBS -l select=1:ncpus=1:mem=8gb
#PBS -l walltime=24:00:00
#PBS -J 1-2

set -e
module load anaconda3/personal

source activate bioperl

cd ~/../ephemeral/gubbins_testing/simul_data/length_tests

LENGTH=$(head -n $PBS_ARRAY_INDEX ~/gubbins_testing/seq_lengths_450_500.txt | tail -n 1)

#if [ $RECCERS == "0.1" ]
#then
#	echo "wassssssssup"
#else

for REP in {1..10}
do
cd "rep_${REP}_data"
## Get the simulation done
bash ~/gubbins_testing/gubbins_sim/bash/simul_script_poisson_JC_VARYING_LENGTH.sh \
0.1 0.5 \
~/gubbins_testing/simul_data/strep_53_uc.aln \
~/gubbins_testing/simul_data/26_phage.mfa \
$LENGTH

cd ../
## Make the IQtree
done

